version: "3.2"

networks:
  ros:
    driver: bridge

services:
  slict:
      image: slictdocker:latest
      build: .
      container_name: slict
      environment:
        - ROS_HOSTNAME=slict
        - ROS_MASTER_URI=http://slict:11311
      command: stdbuf -o L roscore
      networks:
        - ros
      restart: always


  ros_bridge:
    image: osrf/ros:foxy-ros1-bridge      
    container_name: ros1_bridge
    environment:
      - ROS_MASTER_URI=http://slict:11311
      - IGN_IP=slict
    volumes:
      - type: bind
        source: .topics.yaml
        target: /app/setup/topics_config.yaml
    # command: /bin/bash -c '. /opt/ros/noetic/setup.bash && . /opt/ros/foxy/setup.bash && ros2 run ros1_bridge dynamic_bridge --bridge-all-topics'
    command: /bin/bash -c '. /opt/ros/noetic/setup.bash && . /opt/ros/foxy/setup.bash && rosparam load /app/setup/topics_config.yaml && ros2 run ros1_bridge parameter_bridge '
    networks:
      - ros
    depends_on: 
      - slict


