version: "3.2"

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: slictdocker:latest
    container_name: slict
    environment:
      - ROS_HOSTNAME=slict
      - ROS_MASTER_URI=http://slict:11311
      - DISPLAY=${DISPLAY}  # Pass X11 display
      - QT_X11_NO_MITSHM=1  # Prevent shared memory issues in Qt apps
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # Share X11 socket
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  ros_bridge:
    image: bridge-slict     
    container_name: ros1_bridge
    environment:
      - ROS_MASTER_URI=http://slict:11311
      - IGN_IP=slict
    volumes:
      - type: bind
        source: /home/tim/Documents/slict-docker/topics.yaml
        target: /app/setup/topics_config.yaml
      - type: bind
        source: /media/tim/T7 Shield/robot-AA/Scenario-1/scenario1_take_1
        target: /root/data
    command: /bin/bash -c '. /opt/ros/foxy/setup.bash && . /ROS2/install/setup.bash && ros2 bag play /root/data --loop' #&& ros2 run ros1_bridge dynamic_bridge --bridge-all-topics

    networks:
      - ros



